### PR TITLE
Adding GoCD feed foundation for ingest

### PR DESCRIPTION
**Pull request by IanWoodard**
This PR adds the initial functionality that will enable a message to be sent in #discuss-ingest each time either relay (soon to be renamed, we will have to circle back and rename it here once that is done) and relay-pop are deployed. From here, you all are free to extend the functionality to fit your needs.

### CODE REVIEW

**Review by iker-barriocanal — COMMENTED** [review]
What does the message look like? Is there a mechanism to update the message contents?

**Review by jjbayer — APPROVED** [review]
Thanks for this! Let's try it.

**Review by Dav1dde — APPROVED** [review]
Let's try it, but would also be interested in maybe customizing the message.

**Review by olksdr — APPROVED** [review]

**Comment by olksdr** [comment]
> Let's try it, but would also be interested in maybe customizing the message.

@Dav1dde  you definitely wanna have more emoji, don't you?

**Comment by Dav1dde** [comment]
> @Dav1dde you definitely wanna have more emoji, don't you?

We need some randomness, random selection of emojis with random counts. Kind of like an oracle, so we can know how the deployment will go before it's even rolled out.

**Pull request merged**
