### PR TITLE
Fixing migrate

### PR DESCRIPTION
**Pull request by IanWoodard**
Adding a more clear migrate:latest script

### CODE REVIEW

**Review by mattgauntseo-sentry — CHANGES_REQUESTED** [review]
Can you update the migrate command on the README too

**Review by hubertdeng123 — CHANGES_REQUESTED** [review]
I think this will break .github/workflows/migration.yml. That will also need to be changed, are we sure we want to `migrate:latest` everytime?

**Comment by IanWoodard** [comment]
> Can you update the migrate command on the README too

Noticed and fixed

**Comment by IanWoodard** [comment]
> I think this will break .github/workflows/migration.yml. That will also need to be changed, are we sure we want to `migrate:latest` everytime?

I realized this after changing, went for a hybrid approach

**Review by mattgauntseo-sentry — APPROVED** [review]

**Review by hubertdeng123 — APPROVED** [review]

**Pull request merged**
